assignment3/movielens/movielens/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("userview.urls")),
]

assignment3/movielens/userview/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("list", views.IndexView.as_view(), name="movies_list"),
    path("genre/<int:pk>", views.GenreView.as_view(), name="genre_detail"),
    path("movie/<int:pk>", views.MovieView.as_view(), name="movie_detail"),
    path("movie/add", views.movie_add, name="movie_add"),
    path("movie/image/add/<int:movie_id>", views.movie_image_add, name="movie_image_add"),
    path("movie/edit/<int:pk>", views.movie_edit, name="movie_edit"),
    path("rated", views.RatedMoviesView.as_view(), name="rated"),
    path("rating/add/<int:movie_id>", views.rating_add, name="rating_add"),
    path("rating/delete/<int:rating_id>", views.rating_delete, name="rating_delete"),
    path("comment/add/<int:movie_id>", views.comment_add, name="comment_add"),
    path("comment/delete/<int:pk>", views.comment_delete, name="comment_delete"),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    path("search", views.search, name="search"),
    path("admin_page", views.admin_page, name="admin_page"),
    path("", views.home_page, name="home_page"),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

assignment3/movielens/userview/models.py
from django.db import models
from django.conf import settings

class Genre(models.Model):
    name = models.CharField(max_length=300)
    def __str__(self):
        return self.name
    
class Movie(models.Model):
    title = models.CharField(max_length=1000)
    year = models.IntegerField(default=0)
    genres = models.ManyToManyField(Genre)
    director = models.CharField(max_length=200, default='')
    average_rating = models.FloatField(default=0)
    imdbLink = models.CharField(max_length=200, default='')
    description = models.TextField(default='')
    image = models.ForeignKey('MovieImage', on_delete=models.SET_NULL, null=True, blank=True, related_name='movies_with_front_image')

    
class MovieImage(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='movie_images/')

    def __str__(self):
        return f'{self.image.name} ({self.pk})'

class Rating(models.Model):
    value = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # TODO: Add timestamp = models.DateTimeField(auto_now_add=True) # required for get_recently_most_liked_movies
    
class Comment(models.Model):
    text = models.CharField(max_length=1000)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    timestamp = models.IntegerField(default=0)

assignment3/movielens/userview/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import Rating, Movie, Genre, Comment, MovieImage

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm,self).save(commit=False)
        user.email = self.cleaned_data['email']
        
        if commit:
            user.save()
        return user
    
class RatingForm(forms.ModelForm):
    value = forms.IntegerField(min_value=1, max_value=5, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    
    class Meta:
        model = Rating
        fields = ('value',)

class MovieForm(forms.ModelForm):
    image = forms.ModelChoiceField(
        queryset=MovieImage.objects.all(),
        required=False,
        empty_label='No front image'
    )

    genres = forms.ModelMultipleChoiceField(
        queryset=Genre.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Movie
        fields = ['title', 'year', 'genres', 'director', 'imdbLink', 'description', 'image']

class MovieImageForm(forms.ModelForm):
    image = forms.ImageField(max_length=100000000)
    class Meta:
        model = MovieImage
        fields = ['image']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

assignment3/movielens/userview/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.template import loader
from django.shortcuts import get_object_or_404, redirect
from django.views import generic
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .models import Movie, Genre, Rating, Comment, MovieImage
from .forms import NewUserForm, RatingForm, MovieForm, CommentForm, MovieImageForm



def index(request: HttpRequest):
    movies = Movie.objects.order_by('-title')
    template = loader.get_template('userview/movies_list.html')
    context = {
        'movies': movies
    }
    return HttpResponse(template.render(context, request))

def view_movie(request: HttpRequest, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    movie.genres = movie.genres.all()
    template = loader.get_template('userview/movie_detail.html')
    context = {
        'movie': movie
    }
    return HttpResponse(template.render(context, request))

def view_genre(request: HttpRequest, genre_id):
    genre = get_object_or_404(Genre, id=genre_id)
    template = loader.get_template('userview/genre_detail.html')
    context = {
        'genre': genre
    }
    return HttpResponse(template.render(context, request))

class IndexView(generic.ListView):
    paginate_by = 10
    template_name = 'userview/movies_list.html'
    context_object_name = 'movies'
    def get_queryset(self):
        return Movie.objects.order_by('-title')
    
class MovieView(generic.DetailView):
    model = Movie
    template_name = 'userview/movie_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = self.object.genres.all()
        context['comments'] = Comment.objects.filter(movie=self.object)

        context['user_rating'] = 'not rated'
        if self.request.user.is_authenticated:
            rating = Rating.objects.filter(movie=self.object, user=self.request.user)
            if rating:
                context['user_rating'] = rating[0].value
        return context

class GenreView(generic.DetailView):
    model = Genre
    template_name = 'userview/genre_detail.html'

class IndexView(generic.ListView):
    paginate_by = 10
    template_name = 'userview/movies_list.html'
    context_object_name = 'movies'
    def get_queryset(self):
        return Movie.objects.order_by('-title')
    
class RatedMoviesView(LoginRequiredMixin, generic.ListView):
    model = Movie
    template_name = 'userview/rated_movies_list.html'
    context_object_name = 'movies'
    paginate_by = 10

    def get_queryset(self):
        user = self.request.user
        ratings = Rating.objects.filter(user=user)
        movie_ids = ratings.values_list('movie_id', flat=True)
        queryset = Movie.objects.filter(id__in=movie_ids)
        return queryset
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("/")
        return super().dispatch(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for movie in context['movies']:
            movie.rating = Rating.objects.get(movie=movie, user=self.request.user)
        return context

from django.db.models import Avg
def rating_add(request, movie_id):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, id=movie_id)
        if request.method == 'POST':
            form = RatingForm(request.POST)
            if form.is_valid():
                rating_value = form.cleaned_data['value']
                user = request.user
                rating, created = Rating.objects.get_or_create(movie=movie, user=user, defaults={'value': rating_value})
                if not created:
                    rating.value = rating_value
                    rating.save()
                messages.success(request, f'Your rating for {movie.title} has been saved.')
                # updating average rating
                movie_ratings = Rating.objects.filter(movie=movie)
                movie.average_rating = movie_ratings.aggregate(Avg('value'))['value__avg']
                movie.save()
                return redirect('rated')
        else:
            form = RatingForm()
        return render(request, 'userview/rating_add.html', {'form': form, 'movie': movie})
    else:
        return redirect("login")
    
def rating_delete(request, rating_id):
    if request.user.is_authenticated:
        rating = get_object_or_404(Rating, id=rating_id, user=request.user)
        movie = rating.movie
        rating.delete()
        movie_ratings = Rating.objects.filter(movie=movie)
        movie.average_rating = movie_ratings.aggregate(Avg('value'))['value__avg']
        movie.save()
        messages.success(request, f'Your rating for {movie.title} has been deleted.')
        return redirect('rated')
    else:
        return redirect('login')

def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("/")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    
    form = NewUserForm()
    return render(request=request,template_name="userview/register.html",
                                   context={"register_form":form})

def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                messages.success(request, "Login successful.")
                return redirect("/")
            else:
                messages.error(request, "Unsuccessful login. User does not exist")
        messages.error(request, "Unsuccessful login. Invalid information.")
    
    form = AuthenticationForm()
    return render(request=request,template_name="userview/login.html",
                                   context={"login_form":form})


def logout_request(request):
    if not request.user.is_anonymous:
        logout(request)
        messages.success(request, "Logout successful.")
    return redirect("/")

def search(request):
    movie_title = request.GET['title'] if 'title' in request.GET else None
    genre_id = request.GET['genre'] if 'genre' in request.GET else None
    minimum_rating = request.GET['minimum_rating'] if 'minimum_rating' in request.GET else None
    genres = Genre.objects.all()
    if movie_title or genre_id or minimum_rating:
        print("searching for", movie_title, genre_id, "min rating:", minimum_rating, ".")
        movies = Movie.objects.all()
        if movie_title:
            movies = movies.filter(title__icontains=movie_title)
        if genre_id:
            movies = movies.filter(genres__id=genre_id)
        if minimum_rating:
            movies = movies.filter(average_rating__gte=minimum_rating)
            
        return render(request, 'userview/search.html', {'genres': genres, 'movies': movies})
    return render(request, 'userview/search.html', {'genres': genres})       
    
def movie_add(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = MovieForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('/')
        else:
            form = MovieForm()
        return render(request, 'userview/movie_add.html', {'form': form})
    else:
        return redirect("login")

def movie_edit(request, pk):
    if request.user.is_superuser:
        movie = get_object_or_404(Movie, pk=pk)
        if request.method == 'POST':
            form = MovieForm(request.POST, instance=movie)
            if form.is_valid():
                form.save()
                return redirect('movie_detail', pk=pk)
        else:
            form = MovieForm(instance=movie)
        return render(request, 'userview/movie_edit.html', {'form': form})
    else:
        return redirect("login")
    
def comment_add(request, movie_id):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, pk=movie_id)
        if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.movie = movie
                comment.user = request.user
                comment.save()
                return redirect('movie_detail', pk=movie_id)
        else:
            form = CommentForm()
        return render(request, 'userview/comment_add.html', {'form': form})
    else:
        return redirect("login")
    
def comment_delete(request, pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, id=pk)
        movie = comment.movie
        if comment.user != request.user:
            messages.error(request, f'Comments from other users cannot be deleted')
        else:
            comment.delete()
            messages.success(request, f'Comment for {movie.title} has been deleted.')
        return redirect('movie_detail', pk=movie.pk)
    else:
        return redirect("login")

## admin page with a form to add a new movie
def admin_page(request):
    if request.user.is_authenticated and request.user.is_superuser:
        if request.method == 'POST':
            form = MovieForm(request.POST)
            if form.is_valid():
                form.save()

assignment3/movielens/userview/templates/userview/admin_page.html
{% extends "userview/base.html" %}

{% block content %}
{%load crispy_forms_tags %}
<div class="container py-5">
    <h1>Admin Page</h1>
    <h3>New Movie</h3>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Save</button>
    </form>
</div>
{% endblock %}

assignment3/movielens/userview/templates/userview/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}MovieLens{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home_page' %}">MovieLens</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rated' %}">My rated movies</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'movies_list' %}">Movies list</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'search' %}">Search</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto">
          {% if user.is_authenticated %}
            {% if user.is_superuser%}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin_page' %}">Admin page</a>
              </li>
            {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="#">{{ user.username }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">Register</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  
  {% block content %}
  {% endblock %}

  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li {% if message.tags %} class="{{message.tags}}"{% endif %}>
          {{ message }}
      </li>
      {% endfor %}
  </ul>
  {%endif%}
  
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
  </script>
</body>
</html>

assignment3/movielens/userview/templates/userview/comment_add.html
{% extends "userview/base.html" %}

{% block content %}
{%load crispy_forms_tags %}
<div class="container py-5">
    <h1>Add comment</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Add</button>
    </form>
</div>
{% endblock %}

assignment3/movielens/userview/templates/userview/genre_detail.html
{% extends "userview/base.html" %}

{% block content %}
<div class="container mt-5">
  <h1 class="mb-4">{{ genre.name }}</h1>
</div>
{% endblock %}

assignment3/movielens/userview/templates/userview/home.html
{% extends "userview/base.html" %}

{% block content %}
  <header class="bg-primary text-white text-center py-5">
    <h1>Welcome to Movie Lens</h1>
    <p class="lead">Discover and explore your favorite movies, TV shows, and actors.</p>
    <a href="#" class="btn btn-light btn-lg">Get Started</a>
  </header>

  <section class="container my-5">
    <div class="row">
      <div class="col-md-4 mb-4">
        <div class="card">
          <img src="path/to/image.jpg" class="card-img-top" alt="Movie Image">
          <div class="card-body">
            <h5 class="card-title">Movie 1</h5>
            <p class="card-text">A brief description of the movie.</p>
            <a href="#" class="btn btn-primary">Read More</a>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

assignment3/movielens/userview/templates/userview/home_page.html
{% extends "userview/base.html" %}

{% block content %}
{%load crispy_forms_tags %}
<div class="container py-5">
    <h1>Home</h1>

    <h3>Welcome 🎥</h3>
    <p>Discover the magic of cinema with MovieLens, your ultimate guide to movies and their ratings. Explore a vast collection of films, from timeless classics to the latest blockbusters, and find the perfect movie for every occasion.</p>
    <p>Whether you're a passionate cinephile or just looking for entertainment recommendations, MovieLens has you covered. Our comprehensive database provides detailed information about each movie, including ratings, reviews, cast, and more.</p>
    <p>Immerse yourself in the world of storytelling, as you dive into genres that ignite your imagination and characters who capture your heart. From heartwarming tales that inspire, to thrilling adventures that keep you on the edge of your seat, MovieLens brings the cinematic experience right to your screen.</p>
    <p>Unleash your inner movie critic by sharing your thoughts and ratings, and engage in lively discussions with fellow movie enthusiasts. MovieLens is not just a platform—it's a community where ideas are exchanged, friendships are formed, and the love for movies is celebrated.</p>
    <p>Ready to embark on a cinematic journey like no other? Start exploring now and let MovieLens be your trusted companion in the world of movies.</p>
    <a class="button" href="{% url 'register' %}">Get Started</a>

    <div style="height: 5em"></div>

    <h3>Recently popular</h3>
    <div class="list-group">
        {% for movie in recently_popular_movies %}
        <a href="/movie/{{movie.id}}" class="list-group-item list-group-item-action flex-column align-items-start" aria-current="true">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1" style="display: inline-block; width: 50%">{{ movie.title }}</h5>
                  <small>
                    {% if 1 <= movie.average_rating %}⭐{% endif %}
                    {% if 2 <= movie.average_rating %}⭐{% endif %}
                    {% if 3 <= movie.average_rating %}⭐{% endif %}
                    {% if 4 <= movie.average_rating %}⭐{% endif %}
                    {% if 5 <= movie.average_rating %}⭐{% endif %}
                  </small>
                <small style="display: inline-block; width: 20%">
                    {% for genre in movie.genres.all %}
                    {{ genre.name }}
                    {% endfor %}
                </small>
              </div>
          </a>
          {% endfor %}
    </div>

    <div style="height: 5em"></div>

    {% if user.is_authenticated %}
        <h3>Your recommendations</h3>
        <div class="list-group">
          {% for movie in recommendations %}
          <a href="/movie/{{movie.id}}" class="list-group-item list-group-item-action flex-column align-items-start" aria-current="true">
              <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1" style="display: inline-block; width: 50%">{{ movie.title }}</h5>
                    <small>
                      {% if 1 <= movie.average_rating %}⭐{% endif %}
                      {% if 2 <= movie.average_rating %}⭐{% endif %}
                      {% if 3 <= movie.average_rating %}⭐{% endif %}
                      {% if 4 <= movie.average_rating %}⭐{% endif %}
                      {% if 5 <= movie.average_rating %}⭐{% endif %}
                    </small>
                  <small style="display: inline-block; width: 20%">
                      {% for genre in movie.genres.all %}
                      {{ genre.name }}
                      {% endfor %}
                  </small>
                </div>
            </a>
            {% endfor %}
      </div>
    {% endif %}

    <div style="height: 5em"></div>
</div>
{% endblock %}

assignment3/movielens/userview/templates/userview/login.html
{% extends "userview/base.html" %}

{% block content %}
{%load crispy_forms_tags %}
<!--Login-->
<div class="container py-5">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {{ login_form|crispy }}
        <button class="btn btn-primary" type="submit">Login</button>
    </form>
    <p class="text-center">If you don't have an account,
        <a href="/register">register</a> instead.</p>
</div>
{% endblock %}

assignment3/movielens/userview/templates/userview/movie_add.html
{% extends "userview/base.html" %}

{% block content %}
{%load crispy_forms_tags %}
<div class="container py-5">
    <h1>Add movie</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Add</button>
    </form>
</div>
{% endblock %}

assignment3/movielens/userview/templates/userview/movie_detail.html
{% extends "userview/base.html" %}

{% block content %}
<div class="container mt-5">
  <h1 class="mb-4">{{ movie.title }}</h1>

  <h3>Image Gallery:</h3>
  <div id="carouselExampleControls" class="carousel slide" data-interval="false" style="width: 40%;">
    <div class="carousel-inner">
      {% if movie.front_image %}
        <div class="carousel-item active">
          <img class="d-block w-100" src="{{ movie.image.image.url }}" alt="Front Image">
        </div>
        {% for image in movie.movieimage_set.all %}
          <div class="carousel-item">
            <img class="d-block w-100" src="{{ image.image.url }}" alt="Gallery Image">
          </div>
        {% endfor %}
      {% else %}
        {% for image in movie.movieimage_set.all %}
        {% if forloop.first %}
          <div class="carousel-item active">
            <img class="d-block w-100" src="{{ image.image.url }}" alt="Front Image">
          </div>
        {% else %}
          <div class="carousel-item">
            <img class="d-block w-100" src="{{ image.image.url }}" alt="Gallery Image">
          </div>
        {% endif %}
        {% empty %}
          <p>No images available.</p>
        {% endfor %}
      {% endif %}
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  {% if user.is_superuser %}
  <a href="{% url 'movie_image_add' movie.id %}">Add image</a>
  {% endif %}
  
  <p>Average rating: {{ movie.average_rating }}</p>
  {% if user.is_authenticated %}
  <p>Your rating: {{ user_rating }}</p>
  {% endif %}
  <a href="{{ movie.imdbLink }}">IMDB reference: {{ movie.imdbLink }}</a>
  <p><strong>Genres:</strong></p>
  {% for genre in genres %}
    <li><a href="{% url 'genre_detail' genre.id %}">{{ genre.name }}</a></li>
  {% endfor %}
  <p><strong>Comments:</strong></p>
  {% for comment in comments %}
    <li>{{ comment.text }} by {{ comment.user }}
      {% if user == comment.user %}
      <a href="{% url 'comment_delete' comment.pk %}">delete</a>
      {% endif %}
    </li>
  {% endfor %}

  <div class="mt-4" style="height: 10em;">
    {% if user.is_superuser %}
    <a class="action btn btn-secondary" href="{% url 'movie_edit' movie.id %}">Edit Movie</a>
    {% endif %}
    <a class="action btn btn-secondary" href="{% url 'rating_add' movie.id %}">Add Rating</a>
    <a class="action btn btn-secondary" href="{% url 'comment_add' movie.id %}">Add Comment</a>
  </div>

</div>
  
{% endblock %}

assignment3/movielens/userview/templates/userview/movie_edit.html
{% extends "userview/base.html" %}

{% block content %}
{%load crispy_forms_tags %}
<div class="container py-5">
    <h1>Edit movie</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Edit</button>
    </form>
</div>
{% endblock %}

assignment3/movielens/userview/templates/userview/movies_list.html
{% extends "userview/base.html" %}

{% block content %}
<div class="container mt-5">
  <h1 class="mb-4">All Movies</h1>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
      </tr>
    </thead>
    <tbody>
      {% for movie in page_obj %}
        <tr>
          <td>{{ movie.id }}</td>
          <td><a href="{% url 'movie_detail' movie.id %}">{{ movie.title }}</a></td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="2">No movies available.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
  
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
  
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
  </div>
</div>
{% endblock %}

assignment3/movielens/userview/templates/userview/rated_movies_list.html
{% extends "userview/base.html" %}

{% block content %}
<div class="container mt-5">
  <h1 class="mb-4">Rated movies</h1>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Rating</th>
        <th>Delete Rating</th>
      </tr>
    </thead>
    <tbody>
      {% for movie in page_obj %}
        <tr>
          <td>{{ movie.id }}</td>
          <td><a href="{% url 'movie_detail' movie.id %}">{{ movie.title }}</a></td>
          <td>{{ movie.rating.value }}</td>
          <td><a href="{% url 'rating_delete' movie.rating.id %}">delete</a></td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="2">No movies available.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
  
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
  
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
  </div>
</div>
{% endblock %}

assignment3/movielens/userview/templates/userview/rating_add.html
{% extends 'userview/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h1>Add Rating for {{ movie.title }}</h1>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
{% endblock %}